import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AllProviders from "@/components/AllProviders";
import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AllProviders>
          <StoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </StoreProvider>
        </AllProviders>
      </body>
    </html>
  );
}
